feat: Display of the hospital complex map
PSW-Organization-8/hospital-information-system pull request #15
Opened 2021-11-05 13:30 UTC by vikikukic99

Main hospital building, display of hospital complex map

2021-11-05 15:38 UTC, vladimirr9 requested changes

2021-11-05 15:38 UTC, vladimirr9 commented on manager-application/src/app/editor/dashboard.component.ts
> +  selector: 'app-root',
Ne sme selektor da bude app-root, treba da ostane default

2021-11-05 15:38 UTC, vladimirr9 commented on manager-application/src/app/editor/dashboard.component.scss
> +                        z-index: 9999999;
Description mora da se uvek prikaze iznad hover-ovanog elementa

2021-11-07 21:16 UTC, vladimirr9 approved these changes

2021-11-07 21:18 UTC, tara-pogancev approved these changes
Looks good. 🚀

2021-11-07 21:20 UTC, merged